recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    create_shopping_item,
    ShoppingItemListView,
    delete_all_shopping_items,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path(
        "shopping_items/create/", create_shopping_item, name="shoppingitem_new"
    ),
    path(
        "shopping_items/",
        ShoppingItemListView.as_view(),
        name="shoppingitems_list",
    ),
    path(
        "shopping_items/delete/",
        delete_all_shopping_items,
        name="shoppingitems_deleteall",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
        null=True,
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.PositiveSmallIntegerField(null=True)

    def __str__(self):
        return str(self.name) + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(20)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.recipe.name) + " by " + str(self.recipe.author)


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL,
        related_name="shoppingitems",
        on_delete=models.CASCADE,
        null=True,
    )
    food_item = models.ForeignKey(
        "FoodItem",
        related_name="shoppingitems",
        on_delete=models.PROTECT,
        null=True,
    )

    def __str__(self):
        return self.food_item

recipes/forms.py
from django import forms

from recipes.models import Recipe

# we originally needed this when we had function-based views in recipes/views.py.
# but once we moved to class-based views (RecipteCreateView and RecipeUpdateView),
# these are no longer needed
# class RecipeForm(forms.ModelForm):
#     class Meta:
#         model = Recipe
#         fields = [
#             "name",
#             "author",
#             "description",
#             "image",
#         ]


from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from typing import List
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from recipes.forms import RatingForm

# we originally needed this import when we had function-based views.
# but once we moved to class-based views (RecipteCreateView and RecipeUpdateView),
# these are no longer needed
# from recipes.forms import RecipeForm
from recipes.models import Recipe

from recipes.models import Ingredient, ShoppingItem
from django.db import IntegrityError

from django.views.decorators.http import require_http_methods


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 4


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        # Create a new empty list and assign it to a variable
        shoppinglist = []
        # For each item in the user's shopping items, which we
        # can access through the code
        # self.request.user.shopping_items.all()
        # (self is passed in as a parameter to this get_context_data method)
        # (request.user is the current user)
        # (shoppingitems is the related_name we gave to the user property in the ForeignKey within ShoppingItem model)
        # (.all just to get all of shoppingitem instances)
        for item in self.request.user.shoppingitems.all():
            # Add the shopping item's food to the list
            shoppinglist.append(item.food_item)
        # Put that list into the context
        context["shopping_list"] = shoppinglist

        # Strategy: Get the resize request, if it exists, from the request.GET dictionary and put it into the context
        # The self.request.GET property is a dictionary
        # Get the value out of there associated with the key "servings_resize_request_by_user_on_page"
        # (this key is the "name= " in the input tag that I myself assigned it on recipes/detail.html -- see around line 25)
        servings_resize_requested_number = self.request.GET.get(
            "servings_resize_request_by_user_on_page"
        )
        # Store in the context dictionary with the key "servings"
        context["requested_servings"] = servings_resize_requested_number

        return context


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "image", "servings"]
    # success_url = reverse_lazy("recipes_list")

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)

    def form_valid(self, form):
        recipe = form.save(commit=False)
        recipe.author = self.request.user
        recipe.save()
        return redirect("recipe_detail", pk=recipe.id)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "author", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            try:
                rating.recipe = Recipe.objects.get(pk=recipe_id)
            except Recipe.DoesNotExist:
                return redirect("recipes_list")
            rating.save()
    return redirect("recipe_detail", pk=recipe_id)


# This view handles only HTTP POST requests, which means there's no HTML template for it.
# It should create a ShoppingItem instance in the database based on the current user and the value of the submitted "ingredients_id" value.
# https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/04-view-topics/65-shopping-lists.md
# To make it so a function view only handles POST requests, you can use the http_require_methods decorator.
# https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/04-view-topics/67-shopping-lists.md
# (this affects the behavior of the page when the user types /recipes/shopping_items/create on the url address bar)
# (with this @require_http_methods, the user will get a 405 error "The page isn't working")
# (without this @require_http_methods, idk what it would show, but the developer sees a yellow page of sadness: )
# ("DoesNotExist at /recipes/shopping_items/create/"           "Ingredient matching query does not exist."")
@require_http_methods(["POST"])
def create_shopping_item(request):
    # Get the value for the "ingredient_id" from the
    # request.POST dictionary using the "get" method
    ingredientid = request.POST.get("ingredient_id")

    # Get the specific ingredient from the Ingredient model
    # using the code
    # Ingredient.objects.get(id=the value from the dictionary)
    ingredient = Ingredient.objects.get(id=ingredientid)

    # Get the current user which is stored in request.user
    currentuser = request.user

    try:
        # Create the new shopping item in the database
        # using ShoppingItem.objects.create(
        #   food_item= the food item on the ingredient,
        #   user= the current user
        # )
        ShoppingItem.objects.create(
            food_item=ingredient.food,
            user=currentuser,
        )
    except IntegrityError:
        pass

    # Go back to the recipe page with a redirect
    # to the name of the registered recipe detail
    # path with code like this
    # return redirect(
    #     name of the registered recipe detail path,
    #     pk=id of the ingredient's recipe
    # )
    return redirect("recipe_detail", pk=ingredient.recipe.id)


class ShoppingItemListView(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "shopping_items/list.html"

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


# This view handles only HTTP POST requests, which means there's no HTML template for it.
# It should create a ShoppingItem instance in the database based on the current user and the value of the submitted "ingredients_id" value.
# https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/04-view-topics/65-shopping-lists.md
# To make it so a function view only handles POST requests, you can use the http_require_methods decorator.
# https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/04-view-topics/67-shopping-lists.md
# (this affects the behavior of the page when the user types /recipes/shopping_items/create on the url address bar)
# (with this @require_http_methods, the user will get a 405 error "The page isn't working")
@require_http_methods(["POST"])
def delete_all_shopping_items(request):
    # Delete all of the shopping items for the user
    # using code like
    # ShoppingItem.objects.filter(user=the current user).delete()
    ShoppingItem.objects.filter(user=request.user).delete()

    # Go back to the shopping item list with a redirect
    # to the name of the registered shopping item list
    # path with code like this
    # return redirect(
    #     name of the registered shopping item list path
    # )
    return redirect("shoppingitems_list")

recipes/templates/recipes/delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit {{ recipe.name }} - Scrumptious</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Scrumptious</a>
        </li>
        <li>
          <a href="{% url 'tags_list' %}">Tags</a>
        </li>
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li>
          <a href="{% url 'recipe_new' %}">Write a recipe</a>
        </li>
      </ul>
    </nav>
  </header>
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ recipe }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
</body>

</html>

recipes/templates/recipes/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% load resizer %}

  {% block content %}
    <main class="recipe-detail">
      <div>
        <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
        <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
      </div>
      {% if recipe.image %}
        <img src="{{ recipe.image }}" class="pull-right">
      {% endif %}
      <h1>{{ recipe.name }}</h1>
      <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
      <p>
        Created on {{ recipe.created }} |
        Updated on {{ recipe.updated }}
      </p>
      {% if recipe.servings %}
        <p>
          Serves {{ recipe.servings }}
        </p>
        <div>
          <form method="GET">
            {% comment %}
            The "name= " that we give it here, we use on the RecipeDetailView in recipes/views.py
            {% endcomment %}
            <input type="number" name="servings_resize_request_by_user_on_page" required>
            <button>Resize</button>
          </form>
        </div>
      {% endif %}
      <form method="post" action="{% url 'recipe_rating' recipe.id %}">
        {% csrf_token %}
        <div class="rating-form-grid">
          {{ rating_form.as_p }}
          <button class="button">Rate</button>
        </div>
      </form>
      <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
      {{ recipe.description | markdownify }}
      <h2>Ingredients</h2>
      <table>
        <thead>
          <tr>
            <th colspan="2">Amount</th>
            <th>Food item</th>
          </tr>
        </thead>
        <tbody>
          {% for ingredient in recipe.ingredients.all %}
            <tr>
              <td>{{ ingredient|resize_to:requested_servings }}</td>
              <td>{{ ingredient.measure.name }}</td>
              <td>{{ ingredient.food.name }}</td>
              <td>
                {% comment %}
                "if the ingredient's food item is not in the food in the shopping list"
                    (ingredient is the variable we're looping through from the for loop above)
                    (ingredient.food is looking at the food property in the Ingredient model)
                    (shopping_list is a key in the context dictionary in RecipeDetailView)
                  show the + button
                otherwise
                  show the message "in your list"
                {% endcomment %}
                {% if ingredient.food not in shopping_list %}
                  <form method="POST" action="{% url 'shoppingitem_new' %}">
                    {% csrf_token %}
                    <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
                    <button>+ shopping list</button>
                  </form>
                {% else %}
                  in your list
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <h2>Steps</h2>
      <ol>
        {% for step in recipe.steps.all %}
          <li>{{ step.directions }}</li>
        {% endfor %}
      </ol>
    </main>
  {% endblock %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock %}

recipes/templates/recipes/list.html
{% extends 'paginate.html' %}

  {% block content %}
    <main class="recipe-grid">
      {% for recipe in recipe_list %}
        <div class="recipe-card">
          <h2 class="recipe-card-title">
            <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
          </h2>
          <p class="recipe-card-date">{{ recipe.updated }}</p>
        </div>
      {% endfor %}
    </main>
  {% endblock %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock %}

recipes/templates/recipes/test.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

</body>

</html>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

</body>

</html>

{% block %}{% endblock %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

</body>

</html>

{% extends '' %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

</body>
</html>